### ISSUE TITLE
New features are not created

### ISSUE THREAD

**Issue by thymaro** [pvandegeer/GeometryShapes#1]
Normally, when I create a new feature in a polygon layer, a mask appears, and I type in some info about the newly created feature. After drawing a GeometryShape, I get to specify x and y (dimensions in map units), but then the mask just closes and no new feature is created, the mask to type in the feature attributes does not appear. What could be the reason?

QGIS 3.10.4 (LTR)
Windows 10

**Comment by thymaro** [comment]
I tried again. Now the features are created, but the mask to input attribute values is still not shown. Also, after drawing a GeometryShape, the button to save the changes to the layer stays greyed out. If I open the attribute table and input a value in one of the fields and close the attribute table, then I can save the changes. I suspect the plugin saves the changes automatically. Something is going wrong and it's hard to pin it down.

**Comment by pvandegeer** [comment]
Thank you for your bug report. I'm going to look into this and see if I can get it fixed.

**Comment by pvandegeer** [comment]
These's issues should now be fixed. The layer is no longer automatically saved and the save button is activated after adding a feature. The attribute form also pops up after a feature is added. Version 0.6 is now in the qgis repo. Let me know if this solves your issue.

**Comment by thymaro** [comment]
Thanks a lot! I'll have a look at it and report back. It might take some time.

**Comment by samvanemelen** [comment]
I seem to still have this issue in version 0.6. No mask appears and no new features are created after choosing the dimensions.

**Comment by pvandegeer** [comment]
Do you not see the 'rubber band' or mask after first clicking and then moving the cursor? 
Could you provide me with a minimum working layer/workspace where this occurs and/or describe the type of layer you're using, the crs, etc.?
What is your Qgis version and OS?

**Comment by samvanemelen** [comment]
Apologies for the incomplete comment. Qgis version is 3.16.4 on Windows 10. I have the issue with any reference system. But with a bit more testing I found that it only occurs when the file you are editing has a different CRS compared to the project CRS. The issue seems to be that the plugin takes the coordinates of the project screen (mouse position) and saves it as if it was the layer CRS without checking if they are different. Therefor the mask, and the polygon are in fact drawn, but on some other place on the map. Maybe it would be a useful feature if this check was present?

**Comment by pvandegeer** [comment]
Thanks for bringing this to my attention and for finding the cause of this bug.

> The issue seems to be that the plugin takes the coordinates of the project screen (mouse position) and saves it as if it was the layer CRS without checking if they are different. Therefor the mask, and the polygon are in fact drawn, but on some other place on the map. Maybe it would be a useful feature if this check was present?

You're absolutely right. The mask is in the project CRS and the same geometry is written to the active layer, regardless of the layer CRS. I've fixed this for QGIS3 and I'm backporting it to QGIS2 now. I'll release an update soon.

**Comment by pvandegeer** [comment]
Version 0.7 fixes this and is in the QGis plugin repository since last week. Thanks again for reporting this.
